### ISSUE TITLE
Test fails with 'CodedOutputStream was writing to a flat byte array and ran out of space'

### ISSUE THREAD

**Issue by nehaev** [loki4j/loki-logback-appender#188]
Log:

```
09:28:22,645 |-ERROR in com.github.loki4j.client.pipeline.AsyncBufferPipeline@6dc83cf3 - Error occurred while serializing batch #324fc4fd59 (MAX_BYTES, 10 records, 4 streams, est. size 65,535 bytes) java.lang.RuntimeException: Protobuf encoding error
    	at java.lang.RuntimeException: Protobuf encoding error
    	at 	at com.github.loki4j.client.writer.ProtobufWriter.serializeBatch(ProtobufWriter.java:51)
    	at 	at com.github.loki4j.client.pipeline.AsyncBufferPipeline.writeBatch(AsyncBufferPipeline.java:251)
    	at 	at com.github.loki4j.client.pipeline.AsyncBufferPipeline.encodeStep(AsyncBufferPipeline.java:232)
    	at 	at com.github.loki4j.client.pipeline.AsyncBufferPipeline.runEncodeLoop(AsyncBufferPipeline.java:195)
    	at 	at com.github.loki4j.client.pipeline.AsyncBufferPipeline.lambda$start$4(AsyncBufferPipeline.java:122)
    	at 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	at 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at 	at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeStringNoTag(CodedOutputStream.java:2183)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeString(CodedOutputStream.java:1922)
    	at 	at com.google.protobuf.GeneratedMessageV3.writeString(GeneratedMessageV3.java:3294)
    	at 	at com.github.loki4j.pkg.loki.protobuf.Logproto$EntryAdapter.writeTo(Logproto.java:8145)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeMessageNoTag(CodedOutputStream.java:1981)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeMessage(CodedOutputStream.java:1953)
    	at 	at com.github.loki4j.pkg.loki.protobuf.Logproto$StreamAdapter.writeTo(Logproto.java:7239)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeMessageNoTag(CodedOutputStream.java:1981)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeMessage(CodedOutputStream.java:1953)
    	at 	at com.github.loki4j.pkg.loki.protobuf.Logproto$PushRequest.writeTo(Logproto.java:245)
    	at 	at com.github.loki4j.client.writer.ProtobufWriter.endStreams(ProtobufWriter.java:89)
    	at 	at com.github.loki4j.client.writer.ProtobufWriter.serializeBatch(ProtobufWriter.java:49)
    	at 	... 7 common frames omitted
    Caused by: java.lang.ArrayIndexOutOfBoundsException: Failed writing 
     at index 65536
    	at 	at com.google.protobuf.Utf8$UnsafeProcessor.encodeUtf8Direct(Utf8.java:1537)
    	at 	at com.google.protobuf.Utf8$Processor.encodeUtf8(Utf8.java:775)
    	at 	at com.google.protobuf.Utf8.encodeUtf8(Utf8.java:355)
    	at 	at com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder.writeStringNoTag(CodedOutputStream.java:2169)
    	at 	... 18 common frames omitted

com.github.loki4j.logback.integration.GrafanaCloudTest > testJavaProtobufMaxBytesSend FAILED
    java.lang.AssertionError at GrafanaCloudTest.java:130
```

**Comment by nehaev** [comment]
Looks like protobuf-encoded data requires more space than same data encoded with json. The solution is probably to increase internal buffer capacity for protobuf data.
