### ISSUE TITLE
Literal split for labels

### ISSUE THREAD

**Issue by nehaev** [loki4j/loki-logback-appender#4]
Currently `AbstractLoki4jEncoder.extractStreamKVPairs()` ([link](https://github.com/loki4j/loki-logback-appender/blob/main/src/main/java/com/github/loki4j/logback/AbstractLoki4jEncoder.java#L163)) uses `String.split()`, that splits by regex while labels should be splitted by separator literally.

Example of encoder config that is failing because of this issue:

```xml
<label>
    <pattern>level.%level|host.${HOSTNAME}|app."my"app</pattern>
    <pairSeparator>|</pairSeparator>
    <keyValueSeparator>.</keyValueSeparator>
</label>
```

Exception:

```
java.lang.IllegalArgumentException: Unable to split 'l' in 'level.DEBUG|host.anton-desktop|app."my"app' to label key-value pairs, pairSeparator=|, keyValueSeparator=.
        at      at com.github.loki4j.logback.AbstractLoki4jEncoder.extractStreamKVPairs(AbstractLoki4jEncoder.java:171)
        at      at com.github.loki4j.logback.ProtobufEncoder.encodeDynamicLabels(ProtobufEncoder.java:39)
        at      at com.github.loki4j.logback.AbstractLoki4jEncoder.encode(AbstractLoki4jEncoder.java:147)
        at      at com.github.loki4j.logback.AbstractLoki4jEncoder.encode(AbstractLoki4jEncoder.java:17)
        at      at com.github.loki4j.logback.AbstractLoki4jAppender.lambda$handleBatchAsync$2(AbstractLoki4jAppender.java:170)
        at      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)

```

We need either to find a way in the Java standard library to split strings literally, or write our own method for this. The first option is preferable.

**Comment by not-the-avatar** [comment]
i want to try this, where should i begin?

**Comment by nehaev** [comment]
Hey! I've updated the description to make this issue more clear. 

Also, you may want to check the [Contributing guide](https://github.com/loki4j/loki-logback-appender/blob/main/CONTRIBUTING.md).

**Comment by not-the-avatar** [comment]
description is much clearer now, i will try to fix this.

**Comment by not-the-avatar** [comment]
1. we can either escape the pipe `|` character since it is a special character in regex by prefixing the separator with `\\` 

2. or we can use `java.util.regex.Pattern.quote()` to split the string literally
like `String.split(Pattern.quote(separator))` how should i proceed?

**Comment by nehaev** [comment]
For the first option we need to list all the special chars to know what to escape. In second option, `Pattern.quote()` will hopefully do this for us. I think we should try the second option.
