### ISSUE TITLE
The appender tries to send logs before it's possible

### ISSUE THREAD

**Issue by dpetrecki** [loki4j/loki-logback-appender#71]
Hello, I believe I've found an issue or I can propose a nice feature. I have an microservices infrastructure with spring cloud config server serving logs configuration. Everything (service with the appender, config server and Loki) are hosted in AWS ECS and talking to each other using HTTPS. When my service starts, I can see such an error:

```
2021-02-05 12:17:24.781 WARN  [main] org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration - Error opening logging config file https://spring-cloud-config-server-dev.eu-central-1.dev.private:443/application/default/main/logback-spring.xml
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in com.github.loki4j.logback.Loki4jAppender[Loki] - Error while sending Batch #15008f998b (3 records) to Loki (https://loki-dev-eu-central-1.eu-central-1.dev.private:3100/loki/api/v1/push) java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.CompletableFuture$AsyncSupply@46aa7ea6 rejected from java.util.concurrent.ThreadPoolExecutor@272efc52[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:179)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:143)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:123)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
```

The funny thing is - this log is taken from Grafana, which means, everything works fine. All further logs are being sent without such issue.
Sometimes, I can also see this stacktrace just after the application starts:

```
12:17:18,056 |-WARN in com.github.loki4j.logback.Loki4jAppender[Loki] - Error during buffer drain on stop java.util.concurrent.TimeoutException
at java.util.concurrent.TimeoutException
at at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1950)
at at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2085)
at at com.github.loki4j.logback.Loki4jAppender.stop(Loki4jAppender.java:130)
at at ch.qos.logback.core.spi.AppenderAttachableImpl.detachAndStopAllAppenders(AppenderAttachableImpl.java:107)
at at ch.qos.logback.classic.Logger.detachAndStopAllAppenders(Logger.java:206)
at at ch.qos.logback.classic.Logger.recursiveReset(Logger.java:331)
at at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:223)
at at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:348)
at at org.springframework.boot.logging.logback.LogbackLoggingSystem.stopAndReset(LogbackLoggingSystem.java:196)
at at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:163)
at at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
at at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
at at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
at at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.reinitializeLoggingSystem(PropertySourceBootstrapConfiguration.java:143)
at at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:123)
at at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:635)
at at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390)
at at org.springframework.boot.SpringApplication.run(SpringApplication.java:325)
at at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
at at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
```
This one is taken from AWS CloudWatch (so it's not sent to Loki), but all further logs from this machine are being sent without troubles.

Moreover - I also use this appender in the config server and there are no issues at all.
Therefore - I believe the problem is that something strange happens at the beginning, when the context is not started properly yet, or maybe some AWS resources are not connected yet (just guessing - maybe a security group?). The solution I can imagine, is to postpone sending logs for some time when the application starts. I've tried to play with  `batchTimeoutMs` parameter, but postponing all logs is not a solution for me, and it still doesn't work for `Loki4jAppender.stop()` method with hard-coded timeouts.
Or maybe I've made some mistake on my side?

**Comment by dpetrecki** [comment]
I've found the issue in 1.1.0-m1 version. This is about exposing initialDelay and stopDelay variables (hard-coded as 100 and 500 in lines 113 and 130). Unfortunately, it your main branch it's gone and I have no idea, where to look for it. Could you please change those constants to parameters?

**Comment by nehaev** [comment]
Hi, thanks for digging into it and reporting!

This code is now [here](https://github.com/loki4j/loki-logback-appender/blob/main/loki-logback-appender/src/main/java/com/github/loki4j/logback/DefaultPipeline.java#L86) and there's even more hard-coded timeouts in `stop()` method. Looks like this drain-on-stop part needs to be reworked.

Instead of exposing these timeouts to config, I think it might make more sense to expose a boolean setting `drainOnStop`, so user can configure if `stop()` should wait until all remaining messages are sent (for whatever time it takes), or shutdown immediately with all unsent messages dropped and possible `RejectedExecutionException`s in log.

**Comment by dpetrecki** [comment]
Thank you for your answer. I'm not sure about "whatever time it takes", because in some rare cases it can make the application unstoppable. What do you think about ScheduledThreadPool parameters? 100ms doesn't work for me, when I use bootstrap (so logs appears really quick) and HTTPS (so the most of the context has to be present to send first messages).

**Comment by nehaev** [comment]
> I'm not sure about "whatever time it takes", because in some rare cases it can make the application unstoppable.

Do you have any particular cases in mind?

> What do you think about ScheduledThreadPool parameters? 100ms doesn't work for me, when I use bootstrap (so logs appears really quick) and HTTPS (so the most of the context has to be present to send first messages).

`ScheduledThreadPool` periodically runs drain job that checks the following condition:  now - [lastBatchTime](https://github.com/loki4j/loki-logback-appender/blob/v1.0.0/common/src/main/java/com/github/loki4j/common/ConcurrentBatchBuffer.java#L27) > [batchTimeoutMs](https://github.com/loki4j/loki-logback-appender/blob/v1.0.0/loki-logback-appender/src/main/java/com/github/loki4j/logback/Loki4jAppender.java#L32). So timeouts there only affect how often this condition is checked. The batch is being sent only if the condition is met, so you can tune this by editing `batchTimeoutMs` in the config.

**Comment by dpetrecki** [comment]
For the first question - nothing very strict, just an intuition. It just seems like something erroneous. For example, in case of some logback issue or log loop (log created when another log is created), the buffer will never empty. I can just propose to treat e.g. 10 or 30 seconds or even 2 minutes as "whatever time it takes".

About the `batchTimeoutMs`, it affects entire application lifetime, but the issue I'm talking about appears only on startup. As you use `ScheduledExecutorService.scheduleAtFixedRate(Runnable, long, long, TimeUnit)`, increasing the first long value fixes the problem. As it also doesn't seem to me wize to increase it for everybody, it would be grate to have it as a parameter.

**Comment by nehaev** [comment]
> I can just propose to treat e.g. 10 or 30 seconds or even 2 minutes as "whatever time it takes".

The error you've encountered was caused exactly by this: my attempt to find a timeout enough for "typical" send queue to drain, but not too much that log appender prevents the whole app from stopping. Pushing this down to user IMO won't help much, because the idea of having to set timeouts depending on factors you can not predict is bad. `drainOnStop` will offer two consistent options: either we stop immediately (and that's guaranteed), or we wait until everything is drained. If there would be any issues with this, well, at least we will try to fix them in a first place, before falling back to workarounds.

> increasing the first long value fixes the problem

How does it affect you now? Stack traces that you've posted seem to be caused by drain on stop bug.

**Comment by dpetrecki** [comment]
I've copied your code to my project and tried to tweak it a little. The second issue has indeed disappeared after increasing drain on stop timeout. The first one I've fixed by increasing this `ScheduledExecutorService.scheduleAtFixedRate` initial delay. That's why I suppose it's related to the context startup time.

**Comment by nehaev** [comment]
@dpetrecki Could you please check if #75 solves your problem?

**Comment by dpetrecki** [comment]
I'm sorry for holding you but I need some time. Today morning I hoped I can verify it today but I'm not sure now. I'll let you know as soon as possible.

**Comment by dpetrecki** [comment]
OK, I've tested the code and it works pretty well :)! Thank you very much.
When should I expect the release?

**Comment by nehaev** [comment]
Feel free to re-open if anything goes wrong.

> When should I expect the release?

Hopefully within two weeks.

**Comment by dpetrecki** [comment]
Great! Thank you very much:)
